### ISSUE TITLE
Error in starting

### ISSUE THREAD

**Issue by flamendless** [RblSb/KhaHotReload#6]
Hi, im trying to use this outside of vscode and i encounter this error:
```
Running server on 8080
Error: Port 8080 is already in use.
Please close the competing program (maybe another instance of khamake?)
or switch to a different port using the --port argument.
Using Kha (026dfc9f) from /home/brbl/Projects/CodeNect/libs/Kha
Creating Kha project.
Error: khafile.js did not call resolve, no project created.
node:internal/modules/cjs/loader:925
  const err = new Error(message);
              ^

Error: Cannot find module 'libs/hotml/bin/server.js'
Require stack:
- /home/brbl/Projects/CodeNect/libs/Kha/Tools/khamake/out/ProjectFile.js
- /home/brbl/Projects/CodeNect/libs/Kha/Tools/khamake/out/main.js
- /home/brbl/Projects/CodeNect/libs/Kha/Tools/khamake/out/khamake.js
- /home/brbl/Projects/CodeNect/libs/Kha/Tools/khamake/khamake.js
- /home/brbl/Projects/CodeNect/libs/Kha/make.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at eval (eval at <anonymous> (/home/brbl/Projects/CodeNect/libs/Kha/Tools/khamake/out/ProjectFile.js:53:17), <anonymous>:16:17)
    at /home/brbl/Projects/CodeNect/libs/Kha/Tools/khamake/out/ProjectFile.js:53:144
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:75:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/brbl/Projects/CodeNect/libs/Kha/Tools/khamake/out/ProjectFile.js',
    '/home/brbl/Projects/CodeNect/libs/Kha/Tools/khamake/out/main.js',
    '/home/brbl/Projects/CodeNect/libs/Kha/Tools/khamake/out/khamake.js',
    '/home/brbl/Projects/CodeNect/libs/Kha/Tools/khamake/khamake.js',
    '/home/brbl/Projects/CodeNect/libs/Kha/make.js'
  ]
}
```
this is my khafile:
```
let project = new Project("CodeNect");

project.addSources("src");
project.addAssets("assets/DroidSans.ttf");
project.addAssets("assets/test.json");
project.addLibrary("libs/zui");

if (process.argv.includes("--watch")) { // run only in watch mode
	let libPath = project.addLibrary('libs/hotml'); // client code for code-patching
	project.addDefine('js_classic'); // to support constructors patching, optional
	// start websocket server that will send type diffs to client
	const path = require('path');
	if (!libPath) libPath = path.resolve('libs/hotml');
	const Server = require(`${libPath}/bin/server.js`).hotml.server.Main;
	// path to target build folder and main js file.
	const server = new Server(`${path.resolve('.')}/build/${platform}`, 'kha.js');
	callbacks.postHaxeRecompilation = () => {
		server.reload(); // parse js file every compilation
	}
	// for assets reloading
	callbacks.postAssetReexporting = (path) => {
		server.reloadAsset(path);
	}
}

resolve(project);
```

the `hotml` folder is in the `libs/` folder. This is my command for running:
```
	node libs/Kha/make html5 --server & node libs/Kha/make html5 --watch

```

**Comment by flamendless** [comment]
I have managed to get it running by adding `project.localLibraryPath = "libs";` at the beginning of my `khafile.js`. In my browser it seems to be loaded but no hot-reloading seems to be working. Im adding a simple `trace("hi")` in my code but it doesnt show. Only this is shown `kha.js:328 Sources/hotml/client/Client.hx:41: Event: func` each time i saved the modifications.

**Comment by RblSb** [comment]
Hi, sorry for delay. You need to connect to server in your `function main`: `#if hotml new hotml.client.Client(); #end`

**Comment by flamendless** [comment]
I do have that.

Edit:
It seems that relaunching the script and refreshing the tab works.
